server:
  port: 8086
  servlet:
    context-path: /ecommerce
    session:
      timeout: 1m
  tomcat:
    threads:
      max: 200
    uri-encoding: UTF-8
    basedir: /data/logs/training/access_log
    accesslog:
      enabled: true
      pattern: '{"Local IP":"%A","Date time":"%{yyyy-MM-dd HH:mm:ss.SSS}t","Request method":"%m","URL":"%U","HTTP status":%s,"session ID":%S,"Bytes sent":%b,"Process time":%D,"Thread name":"%I"}'
      suffix: .log

spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test_db
    username: root
    password: root
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 2
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      # 不透過@Entity自動化工程建立資料表,經由schema.sql建立資料表與data.sql新增資料
      ddl-auto: none
    properties:
      hibernate:
        # 資料庫方言JPA自動轉換H2相對應的SQL語法     
        #dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        # 查看 JDBC statements、JDBC batches 執行時間統計訊息
        generate_statistics: true
        # The order_inserts property tells Hibernate to take the time to group inserts by entity, creating larger batches.
        # order_inserts 屬性告訴 Hibernate 花時間按實體對插入進行分組，從而創建更大的批次。
        order_inserts: true
        # Can apply the same approach to deletes and updates
        order_updates: true
        jdbc:
          batch_size: 200
          
springboot:
  datasource:
    oracle:
      jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
      username: LOCAL
      password: root
      driverClassName: oracle.jdbc.driver.OracleDriver
      maximumPoolSize: 2
      connectionTimeout: 30000
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/local_db
      username: root
      password: root1234
      driverClassName: com.mysql.cj.jdbc.Driver
      maximumPoolSize: 2
      connectionTimeout: 30000
